name: BE Deploy

on:
  push:
    branches: [ "me", "deploy" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Gradle cache for Docker
        id: gradle_cache
        uses: actions/cache@v4
        with:
          path: ./gradle-cache-dev-home
          key: ${{ runner.os }}-gradle-cache-dev-${{ hashFiles('build.gradle', 'settings.gradle', 'gradle/wrapper/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-dev-

      - name: Restore Gradle cache mounts to BuildKit
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-dir: ./gradle-cache-dev-home
          dockerfile: ./backend/docker/new.Dockerfile
          skip-extraction: ${{ steps.gradle_cache.outputs.cache-hit }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/docker/new.Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/moaon-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push-image
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2025-moaon

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image and deploy
        run: |
          sudo docker compose -f docker/compose.new.yaml up -d
          sudo docker image prune -af
